language: go

env:
- GIMME_OS=linux GIMME_ARCH=386
- GIMME_OS=linux GIMME_ARCH=amd64

install:
- go get ./...
- go get github.com/mattn/go-sqlite3
- go get github.com/boltdb/bolt

script:
- "[ `gofmt -l *.go | wc -l` = 0 ]"
- go build
- go build -tags sqlite
- go build -tags bolt
