[[constraint]]
  branch = "master"
  name = "bazil.org/fuse"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/goftp/server"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
